local function field(spec)
  return spec
end

local S = {
  required_schema_version = 2,

  token_defaults = {
    color = {
      teal = "#208177",
      charcoal = "#333333",
      light_gray = "#dfdfdf",
      near_white = "#f3f3f3",
      title_overlay_text = "#f2f2f2",
      note_text = "rgba(51, 51, 51, 0.78)",
      inline_code_text = "#7a1f1f",
      inline_code_background = "rgba(0, 0, 0, 0.06)",
      code_block_text = "#2b2b2b",
      code_block_background = "rgba(255, 255, 255, 0.45)",
      caption_text = "#666666",
      table_border = "rgba(0, 0, 0, 0.2)",
      table_header_background = "rgba(0, 0, 0, 0.04)",
      annotation_text = "rgba(51, 51, 51, 0.72)",
      annotation_separator = "rgba(0, 0, 0, 0.14)",
      inherit = "inherit",
    },
    spacing = {
      columns_gap = "34px",
      annotations_gap = "0.32em",
      annotations_reserve_gap = "10px",
    },
    typography = {
      base_font_family = '"Noto Sans JP", sans-serif',
      heading_font_family = '"Noto Sans JP", sans-serif',
      presentation_root_font_size = "30px",
      presentation_h1_font_size = "1.95em",
      presentation_h2_font_size = "1.18em",
    }
  },

  fields = {
    field {
      key = "typography.base_font_family",
      path = {"tokens", "typography", "base_font_family"},
      kind = "value",
      default = '"Noto Sans JP", sans-serif',
      css_var = "typography-base-font-family",
    },
    field {
      key = "typography.heading_font_family",
      path = {"tokens", "typography", "heading_font_family"},
      kind = "value",
      default = '"Noto Sans JP", sans-serif',
      css_var = "typography-heading-font-family",
    },
    field {
      key = "typography.presentation_root_font_size",
      path = {"tokens", "typography", "presentation_root_font_size"},
      kind = "value",
      default = "30px",
      css_var = "typography-presentation-root-font-size",
    },
    field {
      key = "typography.presentation_h1_font_size",
      path = {"tokens", "typography", "presentation_h1_font_size"},
      kind = "value",
      default = "1.95em",
      css_var = "typography-presentation-h1-font-size",
    },
    field {
      key = "typography.presentation_h2_font_size",
      path = {"tokens", "typography", "presentation_h2_font_size"},
      kind = "value",
      default = "1.18em",
      css_var = "typography-presentation-h2-font-size",
    },

    field {
      key = "overlay.text",
      path = {"components", "overlay", "text"},
      kind = "string",
      default = "",
      json_path = {"overlay", "text"},
    },
    field {
      key = "overlay.position.default.x",
      path = {"components", "overlay", "position", "default", "x"},
      kind = "value",
      default = "40",
      json_path = {"overlay", "position", "default", "x"},
    },
    field {
      key = "overlay.position.default.y",
      path = {"components", "overlay", "position", "default", "y"},
      kind = "value",
      default = "30",
      json_path = {"overlay", "position", "default", "y"},
    },
    field {
      key = "overlay.position.title.x",
      path = {"components", "overlay", "position", "title", "x"},
      kind = "value",
      default = "70",
      json_path = {"overlay", "position", "title", "x"},
    },
    field {
      key = "overlay.position.title.y",
      path = {"components", "overlay", "position", "title", "y"},
      kind = "value",
      default = "90",
      json_path = {"overlay", "position", "title", "y"},
    },
    field {
      key = "overlay.style.font_size",
      path = {"components", "overlay", "style", "font_size"},
      kind = "value",
      default = "0.7em",
      json_path = {"overlay", "style", "fontSize"},
    },
    field {
      key = "overlay.style.opacity",
      path = {"components", "overlay", "style", "opacity"},
      kind = "value",
      default = "0.85",
      json_path = {"overlay", "style", "opacity"},
    },
    field {
      key = "overlay.style.line_height",
      path = {"components", "overlay", "style", "line_height"},
      kind = "value",
      default = "1.3",
      json_path = {"overlay", "style", "lineHeight"},
    },
    field {
      key = "overlay.style.text_align",
      path = {"components", "overlay", "style", "text_align"},
      kind = "value",
      default = "center",
      json_path = {"overlay", "style", "textAlign"},
    },
    field {
      key = "overlay.style.anchor_x",
      path = {"components", "overlay", "style", "anchor_x"},
      kind = "value",
      default = "center",
      json_path = {"overlay", "style", "anchorX"},
    },
    field {
      key = "overlay.style.title_color",
      path = {"components", "overlay", "style", "title_color_token"},
      kind = "color_token",
      default = "title_overlay_text",
      json_path = {"overlay", "style", "titleColor"},
    },

    field {
      key = "page_number.position.x",
      path = {"components", "page_number", "position", "x"},
      kind = "value",
      default = "1188",
      json_path = {"pageNumber", "position", "x"},
    },
    field {
      key = "page_number.position.y",
      path = {"components", "page_number", "position", "y"},
      kind = "value",
      default = "56",
      json_path = {"pageNumber", "position", "y"},
    },
    field {
      key = "page_number.style.current_font_size",
      path = {"components", "page_number", "style", "current_font_size"},
      kind = "value",
      default = "2.4em",
      json_path = {"pageNumber", "style", "currentFontSize"},
    },
    field {
      key = "page_number.style.total_font_size",
      path = {"components", "page_number", "style", "total_font_size"},
      kind = "value",
      default = "0.9em",
      json_path = {"pageNumber", "style", "totalFontSize"},
    },
    field {
      key = "page_number.style.color",
      path = {"components", "page_number", "style", "color_token"},
      kind = "color_token",
      default = "charcoal",
      json_path = {"pageNumber", "style", "color"},
    },
    field {
      key = "page_number.style.opacity",
      path = {"components", "page_number", "style", "opacity"},
      kind = "value",
      default = "1",
      json_path = {"pageNumber", "style", "opacity"},
    },
    field {
      key = "page_number.style.line_gap",
      path = {"components", "page_number", "style", "line_gap"},
      kind = "value",
      default = "0.2em",
      json_path = {"pageNumber", "style", "lineGap"},
    },
    field {
      key = "page_number.style.text_align",
      path = {"components", "page_number", "style", "text_align"},
      kind = "value",
      default = "center",
      json_path = {"pageNumber", "style", "textAlign"},
    },
    field {
      key = "page_number.style.anchor_x",
      path = {"components", "page_number", "style", "anchor_x"},
      kind = "value",
      default = "center",
      json_path = {"pageNumber", "style", "anchorX"},
    },

    field {
      key = "title_slide.title.x",
      path = {"components", "title_slide", "title", "x"},
      kind = "value",
      default = "96",
      json_path = {"titleSlide", "title", "x"},
    },
    field {
      key = "title_slide.title.y",
      path = {"components", "title_slide", "title", "y"},
      kind = "value",
      default = "226",
      json_path = {"titleSlide", "title", "y"},
    },
    field {
      key = "title_slide.title.font_size",
      path = {"components", "title_slide", "title", "font_size"},
      kind = "value",
      default = "1.55em",
      json_path = {"titleSlide", "title", "fontSize"},
    },
    field {
      key = "title_slide.title.color",
      path = {"components", "title_slide", "title", "color_token"},
      kind = "color_token",
      default = "teal",
      json_path = {"titleSlide", "title", "color"},
    },

    field {
      key = "title_slide.subtitle.x",
      path = {"components", "title_slide", "subtitle", "x"},
      kind = "value",
      default = "96",
      json_path = {"titleSlide", "subtitle", "x"},
    },
    field {
      key = "title_slide.subtitle.y",
      path = {"components", "title_slide", "subtitle", "y"},
      kind = "value",
      default = "320",
      json_path = {"titleSlide", "subtitle", "y"},
    },
    field {
      key = "title_slide.subtitle.font_size",
      path = {"components", "title_slide", "subtitle", "font_size"},
      kind = "value",
      default = "0.96em",
      json_path = {"titleSlide", "subtitle", "fontSize"},
    },
    field {
      key = "title_slide.subtitle.color",
      path = {"components", "title_slide", "subtitle", "color_token"},
      kind = "color_token",
      default = "charcoal",
      json_path = {"titleSlide", "subtitle", "color"},
    },

    field {
      key = "title_slide.author.x",
      path = {"components", "title_slide", "author", "x"},
      kind = "value",
      default = "96",
      json_path = {"titleSlide", "author", "x"},
    },
    field {
      key = "title_slide.author.y",
      path = {"components", "title_slide", "author", "y"},
      kind = "value",
      default = "380",
      json_path = {"titleSlide", "author", "y"},
    },
    field {
      key = "title_slide.author.font_size",
      path = {"components", "title_slide", "author", "font_size"},
      kind = "value",
      default = "0.88em",
      json_path = {"titleSlide", "author", "fontSize"},
    },
    field {
      key = "title_slide.author.color",
      path = {"components", "title_slide", "author", "color_token"},
      kind = "color_token",
      default = "charcoal",
      json_path = {"titleSlide", "author", "color"},
    },

    field {
      key = "title_slide.affiliation.x",
      path = {"components", "title_slide", "affiliation", "x"},
      kind = "value",
      default = "96",
      json_path = {"titleSlide", "affiliation", "x"},
    },
    field {
      key = "title_slide.affiliation.y",
      path = {"components", "title_slide", "affiliation", "y"},
      kind = "value",
      default = "412",
      json_path = {"titleSlide", "affiliation", "y"},
    },
    field {
      key = "title_slide.affiliation.font_size",
      path = {"components", "title_slide", "affiliation", "font_size"},
      kind = "value",
      default = "0.82em",
      json_path = {"titleSlide", "affiliation", "fontSize"},
    },
    field {
      key = "title_slide.affiliation.color",
      path = {"components", "title_slide", "affiliation", "color_token"},
      kind = "color_token",
      default = "charcoal",
      json_path = {"titleSlide", "affiliation", "color"},
    },

    field {
      key = "eyecatch.background.image",
      path = {"components", "eyecatch", "background", "image"},
      kind = "value",
      default = "assets/eyecatch-bg.png",
      resolve_path = "project",
      css_var = "eyecatch-bg-image",
      css_transform = "url",
      runtime_path = {"eyecatch", "background", "image"},
      json_path = {"eyecatch", "background", "image"},
    },
    field {
      key = "eyecatch.background.size",
      path = {"components", "eyecatch", "background", "size"},
      kind = "value",
      default = "contain",
      css_var = "eyecatch-bg-size",
      runtime_path = {"eyecatch", "background", "size"},
      json_path = {"eyecatch", "background", "size"},
    },
    field {
      key = "eyecatch.background.position",
      path = {"components", "eyecatch", "background", "position"},
      kind = "value",
      default = "center",
      css_var = "eyecatch-bg-position",
      runtime_path = {"eyecatch", "background", "position"},
      json_path = {"eyecatch", "background", "position"},
    },

    field {
      key = "eyecatch.title.x",
      path = {"components", "eyecatch", "title", "x"},
      kind = "value",
      default = 165,
      css_var = "eyecatch-title-x",
      css_transform = "length",
      json_path = {"eyecatch", "title", "x"},
    },
    field {
      key = "eyecatch.title.y",
      path = {"components", "eyecatch", "title", "y"},
      kind = "value",
      default = 330,
      css_var = "eyecatch-title-y",
      css_transform = "length",
      json_path = {"eyecatch", "title", "y"},
    },
    field {
      key = "eyecatch.title.max_width",
      path = {"components", "eyecatch", "title", "max_width"},
      kind = "value",
      default = 900,
      css_var = "eyecatch-title-max-width",
      css_transform = "length",
      json_path = {"eyecatch", "title", "maxWidth"},
    },
    field {
      key = "eyecatch.title.font_size",
      path = {"components", "eyecatch", "title", "font_size"},
      kind = "value",
      default = "2.4em",
      css_var = "eyecatch-title-font-size",
      json_path = {"eyecatch", "title", "fontSize"},
    },
    field {
      key = "eyecatch.title.color",
      path = {"components", "eyecatch", "title", "color_token"},
      kind = "color_token",
      default = "charcoal",
      css_var = "eyecatch-title-color",
      json_path = {"eyecatch", "title", "color"},
    },
    field {
      key = "eyecatch.title.font_weight",
      path = {"components", "eyecatch", "title", "font_weight"},
      kind = "value",
      default = "700",
      css_var = "eyecatch-title-font-weight",
      json_path = {"eyecatch", "title", "fontWeight"},
    },
    field {
      key = "eyecatch.title.line_height",
      path = {"components", "eyecatch", "title", "line_height"},
      kind = "value",
      default = "1.1",
      css_var = "eyecatch-title-line-height",
      json_path = {"eyecatch", "title", "lineHeight"},
    },
    field {
      key = "eyecatch.title.letter_spacing",
      path = {"components", "eyecatch", "title", "letter_spacing"},
      kind = "value",
      default = "0",
      css_var = "eyecatch-title-letter-spacing",
      json_path = {"eyecatch", "title", "letterSpacing"},
    },
    field {
      key = "eyecatch.title.anchor_x",
      path = {"components", "eyecatch", "title", "anchor_x"},
      kind = "value",
      default = "left",
      css_var = "eyecatch-title-anchor-x",
      json_path = {"eyecatch", "title", "anchorX"},
    },

    field {
      key = "body.background.image",
      path = {"components", "body_slide", "background", "image"},
      kind = "value",
      default = "assets/body-bg.png",
      resolve_path = "project",
      runtime_path = {"body", "background", "image"},
    },
    field {
      key = "body.background.size",
      path = {"components", "body_slide", "background", "size"},
      kind = "value",
      default = "contain",
      runtime_path = {"body", "background", "size"},
    },
    field {
      key = "body.background.opacity",
      path = {"components", "body_slide", "background", "opacity"},
      kind = "value",
      default = "1.0",
      runtime_path = {"body", "background", "opacity"},
    },

    field { key = "body.slide_heading.x", path = {"components", "body_styles", "slide_heading", "x"}, kind = "css_length", default = 43, css_var = "body-slide-heading-x" },
    field { key = "body.slide_heading.y", path = {"components", "body_styles", "slide_heading", "y"}, kind = "css_length", default = 25, css_var = "body-slide-heading-y" },
    field { key = "body.slide_heading.color", path = {"components", "body_styles", "slide_heading", "color_token"}, kind = "color_token", default = "near_white", css_var = "body-slide-heading-color" },
    field { key = "body.slide_heading.font_size", path = {"components", "body_styles", "slide_heading", "font_size"}, kind = "value", default = "1.04em", css_var = "body-slide-heading-font-size" },
    field { key = "body.slide_heading.font_weight", path = {"components", "body_styles", "slide_heading", "font_weight"}, kind = "value", default = "800", css_var = "body-slide-heading-font-weight" },
    field { key = "body.slide_heading.line_height", path = {"components", "body_styles", "slide_heading", "line_height"}, kind = "value", default = "1.1", css_var = "body-slide-heading-line-height" },
    field { key = "body.slide_heading.letter_spacing", path = {"components", "body_styles", "slide_heading", "letter_spacing"}, kind = "value", default = "-0.02em", css_var = "body-slide-heading-letter-spacing" },

    field { key = "body.content.left", path = {"components", "body_styles", "content_area", "left"}, kind = "css_length", default = 60, css_var = "body-content-left" },
    field { key = "body.content.right", path = {"components", "body_styles", "content_area", "right"}, kind = "css_length", default = 72, css_var = "body-content-right" },
    field { key = "body.content.top", path = {"components", "body_styles", "content_area", "top"}, kind = "css_length", default = 126, css_var = "body-content-top" },
    field { key = "body.content.bottom", path = {"components", "body_styles", "content_area", "bottom"}, kind = "css_length", default = 52, css_var = "body-content-bottom" },
    field { key = "body.content.color", path = {"components", "body_styles", "content_area", "color_token"}, kind = "color_token", default = "charcoal", css_var = "body-content-color" },
    field { key = "body.content.font_size", path = {"components", "body_styles", "content_area", "font_size"}, kind = "value", default = "0.88em", css_var = "body-content-font-size" },
    field { key = "body.content.line_height", path = {"components", "body_styles", "content_area", "line_height"}, kind = "value", default = "1.45", css_var = "body-content-line-height" },

    field { key = "body.h1.color", path = {"components", "body_styles", "headings", "h1", "color_token"}, kind = "color_token", default = "teal", css_var = "body-h1-color" },
    field { key = "body.h1.font_size", path = {"components", "body_styles", "headings", "h1", "font_size"}, kind = "value", default = "1.16em", css_var = "body-h1-font-size" },
    field { key = "body.h1.font_weight", path = {"components", "body_styles", "headings", "h1", "font_weight"}, kind = "value", default = "800", css_var = "body-h1-font-weight" },
    field { key = "body.h1.line_height", path = {"components", "body_styles", "headings", "h1", "line_height"}, kind = "value", default = "1.18", css_var = "body-h1-line-height" },
    field { key = "body.h1.margin_top", path = {"components", "body_styles", "headings", "h1", "margin_top"}, kind = "value", default = "0", css_var = "body-h1-margin-top" },
    field { key = "body.h1.margin_bottom", path = {"components", "body_styles", "headings", "h1", "margin_bottom"}, kind = "value", default = "0.42em", css_var = "body-h1-margin-bottom" },

    field { key = "body.h2.color", path = {"components", "body_styles", "headings", "h2", "color_token"}, kind = "color_token", default = "teal", css_var = "body-h2-color" },
    field { key = "body.h2.font_size", path = {"components", "body_styles", "headings", "h2", "font_size"}, kind = "value", default = "1.08em", css_var = "body-h2-font-size" },
    field { key = "body.h2.font_weight", path = {"components", "body_styles", "headings", "h2", "font_weight"}, kind = "value", default = "800", css_var = "body-h2-font-weight" },
    field { key = "body.h2.line_height", path = {"components", "body_styles", "headings", "h2", "line_height"}, kind = "value", default = "1.18", css_var = "body-h2-line-height" },
    field { key = "body.h2.margin_top", path = {"components", "body_styles", "headings", "h2", "margin_top"}, kind = "value", default = "0.2em", css_var = "body-h2-margin-top" },
    field { key = "body.h2.margin_bottom", path = {"components", "body_styles", "headings", "h2", "margin_bottom"}, kind = "value", default = "0.38em", css_var = "body-h2-margin-bottom" },

    field { key = "body.h3.color", path = {"components", "body_styles", "headings", "h3", "color_token"}, kind = "color_token", default = "teal", css_var = "body-h3-color" },
    field { key = "body.h3.font_size", path = {"components", "body_styles", "headings", "h3", "font_size"}, kind = "value", default = "0.98em", css_var = "body-h3-font-size" },
    field { key = "body.h3.font_weight", path = {"components", "body_styles", "headings", "h3", "font_weight"}, kind = "value", default = "800", css_var = "body-h3-font-weight" },
    field { key = "body.h3.line_height", path = {"components", "body_styles", "headings", "h3", "line_height"}, kind = "value", default = "1.18", css_var = "body-h3-line-height" },
    field { key = "body.h3.margin_top", path = {"components", "body_styles", "headings", "h3", "margin_top"}, kind = "value", default = "0", css_var = "body-h3-margin-top" },
    field { key = "body.h3.margin_bottom", path = {"components", "body_styles", "headings", "h3", "margin_bottom"}, kind = "value", default = "0.35em", css_var = "body-h3-margin-bottom" },

    field { key = "body.h4.color", path = {"components", "body_styles", "headings", "h4", "color_token"}, kind = "color_token", default = "teal", css_var = "body-h4-color" },
    field { key = "body.h4.font_size", path = {"components", "body_styles", "headings", "h4", "font_size"}, kind = "value", default = "0.92em", css_var = "body-h4-font-size" },
    field { key = "body.h4.font_weight", path = {"components", "body_styles", "headings", "h4", "font_weight"}, kind = "value", default = "700", css_var = "body-h4-font-weight" },
    field { key = "body.h4.line_height", path = {"components", "body_styles", "headings", "h4", "line_height"}, kind = "value", default = "1.2", css_var = "body-h4-line-height" },
    field { key = "body.h4.margin_top", path = {"components", "body_styles", "headings", "h4", "margin_top"}, kind = "value", default = "0.2em", css_var = "body-h4-margin-top" },
    field { key = "body.h4.margin_bottom", path = {"components", "body_styles", "headings", "h4", "margin_bottom"}, kind = "value", default = "0.32em", css_var = "body-h4-margin-bottom" },

    field { key = "body.h5.color", path = {"components", "body_styles", "headings", "h5", "color_token"}, kind = "color_token", default = "teal", css_var = "body-h5-color" },
    field { key = "body.h5.font_size", path = {"components", "body_styles", "headings", "h5", "font_size"}, kind = "value", default = "0.86em", css_var = "body-h5-font-size" },
    field { key = "body.h5.font_weight", path = {"components", "body_styles", "headings", "h5", "font_weight"}, kind = "value", default = "700", css_var = "body-h5-font-weight" },
    field { key = "body.h5.line_height", path = {"components", "body_styles", "headings", "h5", "line_height"}, kind = "value", default = "1.2", css_var = "body-h5-line-height" },
    field { key = "body.h5.margin_top", path = {"components", "body_styles", "headings", "h5", "margin_top"}, kind = "value", default = "0.2em", css_var = "body-h5-margin-top" },
    field { key = "body.h5.margin_bottom", path = {"components", "body_styles", "headings", "h5", "margin_bottom"}, kind = "value", default = "0.28em", css_var = "body-h5-margin-bottom" },

    field { key = "body.h6.color", path = {"components", "body_styles", "headings", "h6", "color_token"}, kind = "color_token", default = "teal", css_var = "body-h6-color" },
    field { key = "body.h6.font_size", path = {"components", "body_styles", "headings", "h6", "font_size"}, kind = "value", default = "0.82em", css_var = "body-h6-font-size" },
    field { key = "body.h6.font_weight", path = {"components", "body_styles", "headings", "h6", "font_weight"}, kind = "value", default = "700", css_var = "body-h6-font-weight" },
    field { key = "body.h6.line_height", path = {"components", "body_styles", "headings", "h6", "line_height"}, kind = "value", default = "1.2", css_var = "body-h6-line-height" },
    field { key = "body.h6.margin_top", path = {"components", "body_styles", "headings", "h6", "margin_top"}, kind = "value", default = "0.2em", css_var = "body-h6-margin-top" },
    field { key = "body.h6.margin_bottom", path = {"components", "body_styles", "headings", "h6", "margin_bottom"}, kind = "value", default = "0.24em", css_var = "body-h6-margin-bottom" },

    field { key = "body.text.paragraph_color", path = {"components", "body_styles", "text", "paragraph_color_token"}, kind = "color_token", default = "charcoal", css_var = "body-paragraph-color" },
    field { key = "body.text.paragraph_font_size", path = {"components", "body_styles", "text", "paragraph_font_size"}, kind = "value", default = "1em", css_var = "body-paragraph-font-size" },
    field { key = "body.text.list_color", path = {"components", "body_styles", "text", "list_color_token"}, kind = "color_token", default = "charcoal", css_var = "body-list-color" },
    field { key = "body.text.list_font_size", path = {"components", "body_styles", "text", "list_font_size"}, kind = "value", default = "1em", css_var = "body-list-font-size" },
    field { key = "body.text.link_color", path = {"components", "body_styles", "text", "link_color_token"}, kind = "color_token", default = "teal", css_var = "body-link-color" },
    field { key = "body.text.strong_color", path = {"components", "body_styles", "text", "strong_color_token"}, kind = "color_token", default = "inherit", css_var = "body-strong-color" },
    field { key = "body.text.em_color", path = {"components", "body_styles", "text", "em_color_token"}, kind = "color_token", default = "inherit", css_var = "body-em-color" },
    field { key = "body.text.note_color", path = {"components", "body_styles", "text", "note_color_token"}, kind = "color_token", default = "note_text", css_var = "body-note-color" },
    field { key = "body.text.note_font_size", path = {"components", "body_styles", "text", "note_font_size"}, kind = "value", default = "0.84em", css_var = "body-note-font-size" },

    field { key = "body.code.inline_font_size", path = {"components", "body_styles", "code", "inline_font_size"}, kind = "value", default = "0.92em", css_var = "body-inline-code-font-size" },
    field { key = "body.code.inline_color", path = {"components", "body_styles", "code", "inline_color_token"}, kind = "color_token", default = "inline_code_text", css_var = "body-inline-code-color" },
    field { key = "body.code.inline_background", path = {"components", "body_styles", "code", "inline_background_token"}, kind = "color_token", default = "inline_code_background", css_var = "body-inline-code-background" },
    field { key = "body.code.inline_padding", path = {"components", "body_styles", "code", "inline_padding"}, kind = "value", default = "0.08em 0.28em", css_var = "body-inline-code-padding" },
    field { key = "body.code.block_font_size", path = {"components", "body_styles", "code", "block_font_size"}, kind = "value", default = "0.78em", css_var = "body-code-block-font-size" },
    field { key = "body.code.block_color", path = {"components", "body_styles", "code", "block_color_token"}, kind = "color_token", default = "code_block_text", css_var = "body-code-block-color" },
    field { key = "body.code.block_background", path = {"components", "body_styles", "code", "block_background_token"}, kind = "color_token", default = "code_block_background", css_var = "body-code-block-background" },
    field { key = "body.code.block_padding", path = {"components", "body_styles", "code", "block_padding"}, kind = "value", default = "0.75em 0.95em", css_var = "body-code-block-padding" },
    field { key = "body.code.block_line_height", path = {"components", "body_styles", "code", "block_line_height"}, kind = "value", default = "1.45", css_var = "body-code-block-line-height" },

    field { key = "body.blocks.blockquote_color", path = {"components", "body_styles", "blocks", "blockquote_color_token"}, kind = "color_token", default = "charcoal", css_var = "body-blockquote-color" },
    field { key = "body.blocks.blockquote_font_size", path = {"components", "body_styles", "blocks", "blockquote_font_size"}, kind = "value", default = "0.92em", css_var = "body-blockquote-font-size" },
    field { key = "body.blocks.blockquote_border_color", path = {"components", "body_styles", "blocks", "blockquote_border_color_token"}, kind = "color_token", default = "teal", css_var = "body-blockquote-border-color" },
    field { key = "body.blocks.figure_caption_color", path = {"components", "body_styles", "blocks", "figure_caption_color_token"}, kind = "color_token", default = "caption_text", css_var = "body-figure-caption-color" },
    field { key = "body.blocks.figure_caption_font_size", path = {"components", "body_styles", "blocks", "figure_caption_font_size"}, kind = "value", default = "0.72em", css_var = "body-figure-caption-font-size" },
    field { key = "body.blocks.table_font_size", path = {"components", "body_styles", "blocks", "table_font_size"}, kind = "value", default = "0.78em", css_var = "body-table-font-size" },
    field { key = "body.blocks.table_header_color", path = {"components", "body_styles", "blocks", "table_header_color_token"}, kind = "color_token", default = "charcoal", css_var = "body-table-header-color" },
    field { key = "body.blocks.table_text_color", path = {"components", "body_styles", "blocks", "table_text_color_token"}, kind = "color_token", default = "charcoal", css_var = "body-table-text-color" },
    field { key = "body.blocks.table_border_color", path = {"components", "body_styles", "blocks", "table_border_color_token"}, kind = "color_token", default = "table_border", css_var = "body-table-border-color" },
    field { key = "body.blocks.table_header_background", path = {"components", "body_styles", "blocks", "table_header_background_token"}, kind = "color_token", default = "table_header_background", css_var = "body-table-header-background" },
    field { key = "body.blocks.callout_title_color", path = {"components", "body_styles", "blocks", "callout_title_color_token"}, kind = "color_token", default = "teal", css_var = "body-callout-title-color" },
    field { key = "body.blocks.callout_body_color", path = {"components", "body_styles", "blocks", "callout_body_color_token"}, kind = "color_token", default = "charcoal", css_var = "body-callout-body-color" },

    field { key = "body.layout.columns_gap", path = {"components", "body_styles", "layout", "columns_gap_token"}, kind = "spacing_token", default = "columns_gap", css_var = "body-columns-gap" },

    field { key = "body.annotations.font_size", path = {"components", "body_styles", "annotations", "font_size"}, kind = "value", default = "0.68em", css_var = "body-annotations-font-size" },
    field { key = "body.annotations.color", path = {"components", "body_styles", "annotations", "color_token"}, kind = "color_token", default = "annotation_text", css_var = "body-annotations-color" },
    field { key = "body.annotations.line_height", path = {"components", "body_styles", "annotations", "line_height"}, kind = "value", default = "1.3", css_var = "body-annotations-line-height" },
    field { key = "body.annotations.gap", path = {"components", "body_styles", "annotations", "gap_token"}, kind = "spacing_token", default = "annotations_gap", css_var = "body-annotations-gap" },
    field { key = "body.annotations.separator_color", path = {"components", "body_styles", "annotations", "separator_color_token"}, kind = "color_token", default = "annotation_separator", css_var = "body-annotations-separator-color" },
    field { key = "body.annotations.reserve_gap", path = {"components", "body_styles", "annotations", "reserve_gap_token"}, kind = "spacing_token", default = "annotations_reserve_gap", css_var = "body-annotations-reserve-gap" },
  },
}

return S
